// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4zs-3QKygOCvH-9ZDFtSgISJYMuZ3Ao',
    appId: '1:413767096784:web:3760e44b1c7d282d6101d5',
    messagingSenderId: '413767096784',
    projectId: 'casazenn-e3982',
    authDomain: 'casazenn-e3982.firebaseapp.com',
    storageBucket: 'casazenn-e3982.firebasestorage.app',
    measurementId: 'G-4MSM5R1CDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXMNaJZNay2d_knYAMKcrA0cKNcs1KUzI',
    appId: '1:413767096784:android:1d320ef10c9a83016101d5',
    messagingSenderId: '413767096784',
    projectId: 'casazenn-e3982',
    storageBucket: 'casazenn-e3982.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQVaqqWhwKUFYkfWzropjX7K7RljO037E',
    appId: '1:413767096784:ios:ddc32e17fb07809e6101d5',
    messagingSenderId: '413767096784',
    projectId: 'casazenn-e3982',
    storageBucket: 'casazenn-e3982.firebasestorage.app',
    iosBundleId: 'com.example.casazenn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQVaqqWhwKUFYkfWzropjX7K7RljO037E',
    appId: '1:413767096784:ios:ddc32e17fb07809e6101d5',
    messagingSenderId: '413767096784',
    projectId: 'casazenn-e3982',
    storageBucket: 'casazenn-e3982.firebasestorage.app',
    iosBundleId: 'com.example.casazenn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd4zs-3QKygOCvH-9ZDFtSgISJYMuZ3Ao',
    appId: '1:413767096784:web:39f84294b93765bf6101d5',
    messagingSenderId: '413767096784',
    projectId: 'casazenn-e3982',
    authDomain: 'casazenn-e3982.firebaseapp.com',
    storageBucket: 'casazenn-e3982.firebasestorage.app',
    measurementId: 'G-8VNZE7FMY3',
  );
}
